steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/bugtracker-api/django", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/bugtracker-api/django"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/bugtracker-api/django",
         "-s", "bugtracker-api:us-central1:bugtracker-db-instance",
         "--", "python", "manage.py", "migrate", "--settings=config.settings.gcloud_production"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/bugtracker-api/django",
         "-s", "bugtracker-api:us-central1:bugtracker-db-instance",
         "--", "python", "manage.py", "collectstatic", "--no-input", "--clear", "--settings=config.settings.gcloud_production"]
