# Generated by Django 3.0.11 on 2021-01-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201201_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminvitation',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together=set(),
        ),
    ]
