# Generated by Django 3.0.11 on 2021-01-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210122_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminvitation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('invitee_email', 'team')},
        ),
    ]
