# Generated by Django 3.0.11 on 2021-01-28 15:25

from django.db import migrations
import os


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210125_1223'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        User = get_user_model()

        DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
