apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f local.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 8000
  selector:
    io.kompose.service: django
status:
  loadBalancer: {}
