apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f local.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f local.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: docs
    spec:
      containers:
      - args:
        - /start-docs
        env:
        - name: GOOGLE_OAUTH2_KEY
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_OAUTH2_KEY
              name: envs--local--django
        - name: GOOGLE_OAUTH2_SECRET
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_OAUTH2_SECRET
              name: envs--local--django
        - name: IPYTHONDIR
          valueFrom:
            configMapKeyRef:
              key: IPYTHONDIR
              name: envs--local--django
        - name: USE_DOCKER
          valueFrom:
            configMapKeyRef:
              key: USE_DOCKER
              name: envs--local--django
        image: bugtracking_local_docs
        imagePullPolicy: ""
        name: docs
        ports:
        - containerPort: 7000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
