apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f local.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: docs
  name: docs
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    io.kompose.service: docs
status:
  loadBalancer: {}
