apiVersion: v1
data:
  POSTGRES_DB: bugtracking
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: 7HOAt1wTdYzRtoQTOnrMUuRiiwatw2G6c46HMpZr4LfnokkVt5QIrIHMAC1c6X4i
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ydSmejEJGxMucsdtsEhXrMmhvvOIBjuH
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django-envs--local--postgres
  name: envs--local--postgres
